// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza.Data;

#nullable disable

namespace Pizza.Data.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    partial class PizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pizza.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Chicago Deep Dish Pizza"
                        },
                        new
                        {
                            Id = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Chicago Thin Crust Pizza"
                        },
                        new
                        {
                            Id = 3,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Beer"
                        },
                        new
                        {
                            Id = 4,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Wine"
                        });
                });

            modelBuilder.Entity("Pizza.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "9012 Győr, Vadvirág utca 1.",
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tim@gmail.com",
                            IsDeleted = false,
                            Name = "Tim",
                            PhoneNumber = "+367089712234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "9024 Győr, Ikva utca 14. 1/1",
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tom@gmail.com",
                            IsDeleted = false,
                            Name = "Tom",
                            PhoneNumber = "+367089712234"
                        },
                        new
                        {
                            Id = 3,
                            Address = "9022 Győr, Szent István utca 37. 1/2",
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tod@gmail.com",
                            IsDeleted = false,
                            Name = "Tod",
                            PhoneNumber = "+367089712234"
                        },
                        new
                        {
                            Id = 4,
                            Address = "9028 Győr, József Attila utca 112.",
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "toby@gmail.com",
                            IsDeleted = false,
                            Name = "Toby",
                            PhoneNumber = "+367089712234"
                        },
                        new
                        {
                            Id = 5,
                            Address = "9023 Győr, KOdály Zoltán utca 28. 3/4.",
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@gmail.com",
                            IsDeleted = false,
                            Name = "Jane",
                            PhoneNumber = "+367089712234"
                        });
                });

            modelBuilder.Entity("Pizza.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Pizza.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Layers of sausage, meatballs, pepperoni, freshly shredded mozzarella, chunky tomato sauce, and pecorino romano.",
                            IsDeleted = false,
                            Name = "Chicago Meat Market",
                            PhotoPath = "productImages/1.jpg",
                            Price = 19m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extra sausage, extra cheese, extra good in your mouth.",
                            IsDeleted = false,
                            Name = "Chicago Classic",
                            PhotoPath = "productImages/2.jpg",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pepperoni with Uno's own chunky vine-ripened tomato sauce, mozzarella and imported pecorino romano.",
                            IsDeleted = false,
                            Name = "Prima Pepperoni",
                            PhotoPath = "productImages/3.jpg",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Just what it sounds like.",
                            IsDeleted = false,
                            Name = "Cheese & Tomato",
                            PhotoPath = "productImages/4.jpg",
                            Price = 12m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Italian style beef and pork meatballs, ricotta cheese, fresh mushrooms, freshly shredded mozzarella, housemade marinara, and pecornio romano. Molto bene!",
                            IsDeleted = false,
                            Name = "Meatball & Ricotta",
                            PhotoPath = "productImages/5.jpg",
                            Price = 17m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mozzarella, feta, cheddar, romano, and basil pesto sauce topped with diced tomatoes.",
                            IsDeleted = false,
                            Name = "Four Cheese & Pesto",
                            PhotoPath = "pizzaImages/6.jpg",
                            Price = 15m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Caramelized onions, fresh spinach, sun-dried and plum tomatoes, roasted eggplant, pesto, feta, mozzarella and imported pecorino romano.",
                            IsDeleted = false,
                            Name = "Farmer's Market",
                            PhotoPath = "productImages/7.jpg",
                            Price = 15m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The best of both worlds - an Italian sub in our deep dish crust! Filled with mozzarella, provolone, ham, pepperoni, onions, plum tomatoes and banana peppers, sprinkled with oregano and romano. Served with a side of our house vinaigrette.",
                            IsDeleted = false,
                            Name = "New York Deli",
                            PhotoPath = "productImages/8.jpg",
                            Price = 17m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Grilled chicken breast, red onions, mozzarella, aged cheddar and pecorino romano atop a layer of BBQ sauce. With a drizzle of even more BBQ sauce.",
                            IsDeleted = false,
                            Name = "BBQ Chicken",
                            PhotoPath = "productImages/9.jpg",
                            Price = 14m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh mozzarella and basil with our housemade pizza sauce.",
                            IsDeleted = false,
                            Name = "Margherita",
                            PhotoPath = "productImages/10.jpg",
                            Price = 11m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Say aloha to this hot mama of a Hawaiian. We start with a layer of sweet red chili sauce, then add ham, fresh pineapple chunks, jalapeños, mozzarella, aged cheddar, and pecorino romano and finish it with a drizzle of ranch.",
                            IsDeleted = false,
                            Name = "Spicy Hawaiian",
                            PhotoPath = "productImages/11.jpg",
                            Price = 14m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "If you're a fan of cheese and garlic (and really, who isn't?), you'll love this white pizza with creamy ricotta, aged cheddar, mozzarella, romano, extra virgin olive oil, and seasoned garlic.",
                            IsDeleted = false,
                            Name = "Bianco Love",
                            PhotoPath = "productImages/12.jpg",
                            Price = 14m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Our crispy cauliflower crust topped with jalapenos, salsa, spiced beef, grated mozzarella and cheddar cheeses. Baked to perfection and topped with chopped lettuce and tomatoes. Served with sour cream and salsa.",
                            IsDeleted = false,
                            Name = "Taco",
                            PhotoPath = "productImages/13.jpg",
                            Price = 16m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Light and refreshing, Easy Street Wheat is an unfiltered American-style wheat beer. Leaving in the yeast gives the beer a nice, smooth finish and a slightly citrusy flavor.",
                            IsDeleted = false,
                            Name = "Easy Street",
                            PhotoPath = "productImages/14.jpg",
                            Price = 5m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Blue Moon Belgian White, Belgian-style wheat ale, is a refreshing, medium-bodied, unfiltered Belgian-style wheat ale spiced with fresh coriander and orange peel for a uniquely complex taste and an uncommonly smooth finish.",
                            IsDeleted = false,
                            Name = "Belgian White",
                            PhotoPath = "productImages/15.jpg",
                            Price = 5m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A shandy is beer mixed with a little something extra like soda, juice or ginger ale. Leinenkugel’s® Summer Shandy® is a traditional wheat beer with refreshing natural lemonade flavor that makes it perfect for the sun-splashed summer months. For a fun and fresh food pairing, try it with lighter, brighter foods like shrimp quesadillas, pan-seared scallops with lemon vinaigrette, or lemon chicken with pasta.",
                            IsDeleted = false,
                            Name = "Summer Shandy",
                            PhotoPath = "productImages/16.jpg",
                            Price = 5m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "California",
                            IsDeleted = false,
                            Name = "Mark West Pinot Noir",
                            PhotoPath = "productImages/17.jpg",
                            Price = 30m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "California",
                            IsDeleted = false,
                            Name = "Trinity Oaks Merlot",
                            PhotoPath = "productImages/18.jpg",
                            Price = 25m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "California",
                            IsDeleted = false,
                            Name = "Canyon Road Cabernet",
                            PhotoPath = "productImages/19.jpg",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("Pizza.Data.Entities.ProductOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 5,
                            DateOfCreation = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfUpdate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            ProductId = 14
                        });
                });

            modelBuilder.Entity("Pizza.Data.Entities.Order", b =>
                {
                    b.HasOne("Pizza.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pizza.Data.Entities.Product", b =>
                {
                    b.HasOne("Pizza.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pizza.Data.Entities.ProductOrder", b =>
                {
                    b.HasOne("Pizza.Data.Entities.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pizza.Data.Entities.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pizza.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pizza.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pizza.Data.Entities.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("Pizza.Data.Entities.Product", b =>
                {
                    b.Navigation("ProductOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
